name: friendli-provider
kind: model-provider
version: 1.0.2
description: Friendli Model APIs provide instant access to a curated set of models, powered by a proprietary inference stack called Friendli Engine for high-performance, cost-efficient inference.
author: Lee-Si-Yoon
